version: "3.9"

services:
  backend:
    image: python:3.11-slim
    container_name: alphabot-backend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./alphabot-back:/app
    env_file:
      - ./.env
    environment:
      PYTHONUNBUFFERED: "1"
    command: >
      bash -lc "pip install --no-cache-dir -r requirements.txt && \
      uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
